# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import prefix_string_var as prefix_string_var
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import (
    any_keyed_iterables_are_skips as any_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_mep.tasks.reporting import (
    generate_source_voltage_report as generate_source_voltage_report,
)
from ecoscope_workflows_ext_mep.tasks.results import (
    plot_historic_voltage as plot_historic_voltage,
)
from ecoscope_workflows_ext_ste.tasks.filter import (
    flexible_previous_period as flexible_previous_period,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks.io import get_file_path as get_file_path
from ecoscope_workflows_ext_ste.tasks.transformation import (
    column_first_unique_value as column_first_unique_value,
)
from ecoscope_workflows_ext_ste.tasks.transformation import safe_string as safe_string
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[{"index_name": "name"}], **(params.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    subject_group_var = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("subject_group_var")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("subject_group_var") or {}))
        .call()
    )

    subject_observations = (
        task(get_subjectgroup_observations)
        .validate()
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=time_range,
            subject_group_name=subject_group_var,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params.get("subject_observations") or {}),
        )
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    convert_relocs_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_relocs_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_observations,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_relocs_timezone") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_relocs_timezone,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__hex",
                "extra__subject__sex",
                "extra__created_at",
                "extra__subject__subject_subtype",
                "extra__subjectsource__id",
                "extra__subjectsource__assigned_range",
                "extra__observation_details",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    set_previous_period = (
        task(flexible_previous_period)
        .validate()
        .set_task_instance_id("set_previous_period")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(timerange=time_range, **(params.get("set_previous_period") or {}))
        .call()
    )

    previous_subject_observations = (
        task(get_subjectgroup_observations)
        .validate()
        .set_task_instance_id("previous_subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=set_previous_period,
            subject_group_name=subject_group_var,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params.get("previous_subject_observations") or {}),
        )
        .call()
    )

    convert_prev_relocs_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_prev_relocs_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=previous_subject_observations,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_prev_relocs_timezone") or {}),
        )
        .call()
    )

    previous_subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("previous_subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_prev_relocs_timezone,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__hex",
                "extra__subject__sex",
                "extra__created_at",
                "extra__subject__subject_subtype",
                "extra__subjectsource__id",
                "extra__subjectsource__assigned_range",
                "extra__observation_details",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("previous_subject_reloc") or {}),
        )
        .call()
    )

    sort_curr_relocs = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_curr_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_reloc,
            column_name="fixtime",
            ascending=True,
            na_position="last",
            **(params.get("sort_curr_relocs") or {}),
        )
        .call()
    )

    persist_relocs_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_relocs_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_curr_relocs,
            filetype="geoparquet",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="relocations",
            **(params.get("persist_relocs_geoparquet") or {}),
        )
        .call()
    )

    sort_prev_relocs = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_prev_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=previous_subject_reloc,
            column_name="fixtime",
            ascending=True,
            na_position="last",
            **(params.get("sort_prev_relocs") or {}),
        )
        .call()
    )

    persist_prev_relocs_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_prev_relocs_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_prev_relocs,
            filetype="geoparquet",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="previous_period_relocations",
            **(params.get("persist_prev_relocs_geoparquet") or {}),
        )
        .call()
    )

    extract_current_voltage = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_current_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_curr_relocs,
            column_name="observation_details",
            field_name_options=["battery", "mainVoltage", "batt", "power"],
            output_type="float",
            output_column_name="voltage",
            **(params.get("extract_current_voltage") or {}),
        )
        .call()
    )

    extract_previous_voltage = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_previous_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_prev_relocs,
            column_name="observation_details",
            field_name_options=["battery", "mainVoltage", "batt", "power"],
            output_type="float",
            output_column_name="voltage",
            **(params.get("extract_previous_voltage") or {}),
        )
        .call()
    )

    split_current_relocs = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_current_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_current_voltage,
            groupers=groupers,
            **(params.get("split_current_relocs") or {}),
        )
        .call()
    )

    split_previous_relocs = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_previous_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_previous_voltage,
            groupers=groupers,
            **(params.get("split_previous_relocs") or {}),
        )
        .call()
    )

    unique_subject_name = (
        task(column_first_unique_value)
        .validate()
        .set_task_instance_id("unique_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="name", **(params.get("unique_subject_name") or {}))
        .mapvalues(argnames=["df"], argvalues=split_current_relocs)
    )

    safe_subject_name = (
        task(safe_string)
        .validate()
        .set_task_instance_id("safe_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("safe_subject_name") or {}))
        .mapvalues(argnames=["value"], argvalues=unique_subject_name)
    )

    voltage_filename = (
        task(prefix_string_var)
        .validate()
        .set_task_instance_id("voltage_filename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="_historic_voltage.html", **(params.get("voltage_filename") or {}))
        .mapvalues(argnames=["prefix"], argvalues=safe_subject_name)
    )

    zip_current_prev_name = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_current_prev_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[split_current_relocs, split_previous_relocs],
            **(params.get("zip_current_prev_name") or {}),
        )
        .call()
    )

    draw_historic_voltage = (
        task(plot_historic_voltage)
        .validate()
        .set_task_instance_id("draw_historic_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="voltage", **(params.get("draw_historic_voltage") or {}))
        .mapvalues(
            argnames=["current_relocs", "previous_relocs"],
            argvalues=zip_current_prev_name,
        )
    )

    historic_voltage_text = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("historic_voltage_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[voltage_filename, draw_historic_voltage],
            **(params.get("historic_voltage_text") or {}),
        )
        .call()
    )

    persist_collar_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_collar_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix=None,
            **(params.get("persist_collar_html") or {}),
        )
        .mapvalues(argnames=["filename", "text"], argvalues=historic_voltage_text)
    )

    collared_voltage_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("collared_voltage_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Collar Voltage", **(params.get("collared_voltage_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_collar_html)
    )

    grouped_collared_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_collared_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=collared_voltage_widget,
            **(params.get("grouped_collared_widget") or {}),
        )
        .call()
    )

    convert_collar_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_collar_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_collar_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_collar_html)
    )

    persist_collar_template = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("persist_collar_template")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/ywlnnl3dvnqncrh2uzif0/source_voltage_report.docx?rlkey=2m0dtzr6hf5ll2sn3yaq8z5rt&st=avvjku8o&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("persist_collar_template") or {}),
        )
        .call()
    )

    logo_path = (
        task(get_file_path)
        .validate()
        .set_task_instance_id("logo_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("logo_path") or {}),
        )
        .call()
    )

    generate_word_report = (
        task(generate_source_voltage_report)
        .validate()
        .set_task_instance_id("generate_word_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            org_logo_path=logo_path,
            report_period=time_range,
            prepared_by="Ecoscope",
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            template_path=persist_collar_template,
            filename="overall_report.docx",
            **(params.get("generate_word_report") or {}),
        )
        .call()
    )

    collar_voltage_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("collar_voltage_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[grouped_collared_widget],
            time_range=time_range,
            groupers=groupers,
            **(params.get("collar_voltage_dashboard") or {}),
        )
        .call()
    )

    return collar_voltage_dashboard
